version: '3.2'

services:
    api:
        build: api-service
        ports:
            - "8000:8000"
        links:
            - postgres
        restart: always

    postgres:
        image: postgres:10.4-alpine
        container_name: matsim_stats_postgres
        environment:
            # TODO: specify externally
            POSTGRES_PASSWORD: password
            POSTGRES_DB: matsim_stats_db
        ports:
            - "27017:27017"
        restart: always

    superset:
        image: amancevice/superset:0.26.3
        container_name: matsim_stats_superset
        volumes:
            - ./superset/config/:/etc/superset/
            - ./superset/db/:/var/lib/superset/
        ports:
            - "8088:8088"
        links:
            - postgres
        depends_on:
            - redis

    dash:
        build: dash
        container_name: matsim_stats_dash
        volumes:
            - ./dash/src/:/app/src/
        ports:
            - "8050:8050"
        depends_on:
            - redis
        restart: always

    redis:
        image: redis
        restart: always
        volumes:
            - redis:/data
        ports:
            - "6379:6379"

volumes:
    redis:
        external: false
