version: '3.2'

services:
    api:
        build: api-service
        restart: always
        depends_on:
            - postgres

    postgres:
        image: postgres:10.4-alpine
        container_name: matsim_stats_postgres
        environment:
            # TODO: specify externally
            POSTGRES_PASSWORD: password
            POSTGRES_DB: matsim_stats_db
        restart: always

    superset:
        image: amancevice/superset:0.26.3
        container_name: matsim_stats_superset
        volumes:
            - ./superset/config/:/etc/superset/
            - ./superset/db/:/var/lib/superset/
        depends_on:
            - redis

    dash:
        build: dash
        container_name: matsim_stats_dash
        volumes:
            - ./dash/src/:/app/src/
        depends_on:
            - redis
            - postgres
            - api
        restart: always

    redis:
        image: redis
        restart: always
        volumes:
            - redis:/data

    loadbalancer:
        image: nginx:stable-alpine
        container_name: matsim_stats_nginx
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d:ro
        ports:
            - "80:80"
        depends_on:
            - dash
            - api
        restart: always

volumes:
    redis:
        external: false
