version: '3.2'

services:
    api:
        build: api-service
        ports:
            - "8000:8000"
        links:
            - postgres
        restart: always

    postgres:
        image: postgres:10.4-alpine
        environment:
            # TODO: specify externally
            POSTGRES_PASSWORD: password
            POSTGRES_DB: matsim_stats_db
        ports:
            - "27017:27017"
        restart: always

    superset:
        image: amancevice/superset:0.26.3
        container_name: matsim_stats_superset
        volumes:
            - type: bind
              source: ./superset/config/
              target: /etc/superset/
            - type: volume
              source: superset_logs
              target: /var/lib/superset
        ports:
            - "8088:8088"
        links:
            - postgres

volumes:
    superset_logs:
