version: '3.2'

services:
    mongo:
        environment:
            - MONGO_DATA_DIR=/data/db
        volumes:
            - type: volume
              source: mongodb_matsim
              target: /data/db 

volumes:
    mongodb_matsim:
