version: '3.2'

services:
    api:
        build: api-service
        container_name: matsim_stats_api
        restart: always
        env_file:
            - env/ipinfo.env
        depends_on:
            - postgres

    postgres:
        image: postgres:10.4-alpine
        container_name: matsim_stats_postgres
        environment:
            # TODO: specify externally
            POSTGRES_PASSWORD: password
            POSTGRES_DB: matsim_stats_db
        restart: always

    dash:
        build: dash
        container_name: matsim_stats_dash
        volumes:
            - ./dash/src/:/app/src/
        depends_on:
            - redis
            - postgres
            - api
        restart: always

    redis:
        image: redis
        container_name: matsim_stats_redis
        restart: always
        volumes:
            - redis:/data

    nginx:
        image: nginx:1.14.0-alpine
        container_name: matsim_stats_nginx
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d:ro
        ports:
            - "80:80"
        depends_on:
            - dash
            - api
        restart: always

volumes:
    redis:
        external: false
