version: '3'

services:
    api:
        build: api-service
        ports:
            - "8000:8000"
        links:
            - mongo
        restart: always

    mongo:
        image: mongo:4.0.0-xenial
        # TODO: credentials/setup?
        container_name: matsim_stats_mongo
        environment:
            - MONGO_DATA_DIR=/data/db
        volumes:
            - mongodb_matsim:/data/db 
        ports:
            - "27017:27017"
        restart: always
        command: --smallfiles

volumes:
    mongodb_matsim:
