version: '3.2'

services:
    api:
        build: api-service
        ports:
            - "8000:8000"
        links:
            - postgres
        restart: always

    postgres:
        image: postgres:10.4-alpine
        environment:
            # TODO: specify externally
            POSTGRES_PASSWORD: password
            POSTGRES_DB: matsim_stats_db
        ports:
            - "27017:27017"
        restart: always
